# Generated by Django 5.2.8 on 2026-05-01 10:04

from django.db import migrations, models


def set_initial_sort_order(apps, schema_editor):
    Habit = apps.get_model("habits", "Habit")
    user_ids = Habit.objects.values_list("user_id", flat=True).distinct()
    for user_id in user_ids:
        user_habits = Habit.objects.filter(user_id=user_id).order_by("name", "id")
        for index, habit in enumerate(user_habits, start=1):
            habit.sort_order = index
            habit.save(update_fields=["sort_order"])


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ['sort_order', 'name']},
        ),
        migrations.AddField(
            model_name='habit',
            name='category',
            field=models.CharField(choices=[('health', 'Health'), ('study', 'Study'), ('work', 'Work'), ('personal', 'Personal')], default='personal', max_length=12),
        ),
        migrations.AddField(
            model_name='habit',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=6),
        ),
        migrations.AddField(
            model_name='habit',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='habit',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(set_initial_sort_order, migrations.RunPython.noop),
    ]
