# Generated by Django 5.2.8 on 2026-05-01 12:40

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import migrations, models


def migrate_completion_percentages(apps, schema_editor):
    HabitCompletion = apps.get_model("habits", "HabitCompletion")
    for completion in HabitCompletion.objects.all():
        percent = 100 if completion.completed else 0
        completion.completion_percentage = percent
        completion.raw_value = percent
        completion.save(update_fields=["completion_percentage", "raw_value"])


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_alter_habit_options_habit_category_habit_priority_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="habit_type",
            field=models.CharField(
                choices=[
                    ("binary", "Binary (Done / Not Done)"),
                    ("partial", "Partial (0-100%)"),
                    ("quantitative", "Quantitative (Target value)"),
                ],
                default="binary",
                max_length=14,
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="target_value",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name="habit",
            name="unit",
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name="habitcompletion",
            name="completion_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                validators=[MinValueValidator(0), MaxValueValidator(100)],
            ),
        ),
        migrations.AddField(
            model_name="habitcompletion",
            name="raw_value",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.RunPython(migrate_completion_percentages, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="habitcompletion",
            name="completed",
        ),
    ]
