# Generated by Django 5.2.8 on 2026-05-10 00:00

from django.db import migrations, models

CATEGORY_DEFINITIONS = [
    ("health", "Health"),
    ("study", "Study"),
    ("work", "Work"),
    ("personal", "Personal"),
    ("organize", "Organize"),
    ("good-deeds", "Good deeds"),
    ("self-development", "Self development"),
    ("for-her-sake", "For her sake"),
]


def seed_categories(apps, schema_editor):
    HabitCategory = apps.get_model("habits", "HabitCategory")
    Habit = apps.get_model("habits", "Habit")

    categories_by_key = {}
    for index, (key, label) in enumerate(CATEGORY_DEFINITIONS, start=1):
        category, created = HabitCategory.objects.get_or_create(
            key=key,
            defaults={"label": label, "sort_order": index},
        )
        updates = {}
        if not created:
            if category.label != label:
                updates["label"] = label
            if category.sort_order != index:
                updates["sort_order"] = index
        if updates:
            for field, value in updates.items():
                setattr(category, field, value)
            category.save(update_fields=list(updates.keys()))
        categories_by_key[key] = category

    for habit in Habit.objects.all():
        key = getattr(habit, "category", None)
        category = categories_by_key.get(key)
        if category:
            habit.categories.add(category)


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_habit_types_and_progress"),
    ]

    operations = [
        migrations.CreateModel(
            name="HabitCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.SlugField(max_length=32, unique=True)),
                ("label", models.CharField(max_length=40)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "label"],
            },
        ),
        migrations.AddField(
            model_name="habit",
            name="categories",
            field=models.ManyToManyField(blank=True, related_name="habits", to="habits.habitcategory"),
        ),
        migrations.RunPython(seed_categories, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="habit",
            name="category",
        ),
    ]
