# Generated by Django 5.2.8 on 2026-05-18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0005_friendrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="HabitPause",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "habit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pauses",
                        to="habits.habit",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
                "indexes": [
                    models.Index(fields=["habit", "start_date"], name="habits_pause_habit_start_idx"),
                    models.Index(fields=["habit", "end_date"], name="habits_pause_habit_end_idx"),
                ],
            },
        ),
    ]
