# Generated by Django 5.2.8 on 2026-05-18

from django.db import migrations, models
from django.utils import timezone


def dedupe_active_pauses(apps, schema_editor):
    HabitPause = apps.get_model("habits", "HabitPause")
    today = timezone.localdate()
    habit_ids = (
        HabitPause.objects.filter(end_date__isnull=True)
        .values_list("habit_id", flat=True)
        .distinct()
    )
    for habit_id in habit_ids:
        active_pauses = list(
            HabitPause.objects.filter(habit_id=habit_id, end_date__isnull=True)
            .order_by("-start_date", "-id")
        )
        for pause in active_pauses[1:]:
            pause.end_date = max(pause.start_date, today)
            pause.save(update_fields=["end_date"])


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0006_habit_pause"),
    ]

    operations = [
        migrations.RunPython(dedupe_active_pauses, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="habitpause",
            constraint=models.UniqueConstraint(
                fields=["habit"],
                condition=models.Q(end_date__isnull=True),
                name="habits_pause_active_unique",
            ),
        ),
    ]
