# Generated by Django 5.2.8 on 2026-05-25

from django.db import migrations

CATEGORY_DEFINITIONS = [
    ("health", "Health"),
    ("study", "Study"),
    ("organize", "Organize"),
    ("good-deeds", "Good deeds"),
    ("self-development", "Self development"),
    ("spiritual", "Spiritual"),
]

REMOVE_KEYS = {"work", "personal", "for-her-sake"}


def update_categories(apps, schema_editor):
    HabitCategory = apps.get_model("habits", "HabitCategory")

    for index, (key, label) in enumerate(CATEGORY_DEFINITIONS, start=1):
        category, created = HabitCategory.objects.get_or_create(
            key=key,
            defaults={"label": label, "sort_order": index},
        )
        updates = {}
        if not created:
            if category.label != label:
                updates["label"] = label
            if category.sort_order != index:
                updates["sort_order"] = index
        if updates:
            for field, value in updates.items():
                setattr(category, field, value)
            category.save(update_fields=list(updates.keys()))

    HabitCategory.objects.filter(key__in=REMOVE_KEYS).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0007_habit_pause_active_unique"),
    ]

    operations = [
        migrations.RunPython(update_categories, migrations.RunPython.noop),
    ]
