# Generated by Django 5.2.8 on 2026-08-28 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0014_progresssharing'),
        ('habits', '0014_repair_stale_quantity_plan_mirrors'),
    ]

    operations = [
    ]
